name: mempool-fetcher
on: push
jobs:
  fetch-mempool-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: get one day mempool data
        run: ./download_mempool_custom.sh --hour-range 20240313:00-01
      - name: Gunzip data
        run: gunzip *.csv.gz
        working-directory: ./data
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Filter missing data
        run: python filter-private-transactions.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          author_email: 71893015+Amit0617@users.noreply.github.com
          message: 'uploading file'
          add: '*.csv'
