name: mempool-fetcher
on: push
jobs:
  fetch-mempool-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: get one day mempool data
        run: ./download_mempool_custom.sh --hour-range 20240313:00-01
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'uploading file'
          add: '*.csv.gz'
